2025-01-26 19:42:08,469 INFO    MainThread:37356 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-26 19:42:08,470 INFO    MainThread:37356 [wandb_setup.py:_flush():68] Configure stats pid to 37356
2025-01-26 19:42:08,470 INFO    MainThread:37356 [wandb_setup.py:_flush():68] Loading settings from C:\Users\82102\.config\wandb\settings
2025-01-26 19:42:08,470 INFO    MainThread:37356 [wandb_setup.py:_flush():68] Loading settings from G:\My Drive\Git\class_10623\hw0\handout\wandb\settings
2025-01-26 19:42:08,470 INFO    MainThread:37356 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-26 19:42:08,471 INFO    MainThread:37356 [wandb_init.py:setup_run_log_directory():624] Logging user logs to G:\My Drive\Git\class_10623\hw0\handout\wandb\run-20250126_194208-allzpf61\logs\debug.log
2025-01-26 19:42:08,471 INFO    MainThread:37356 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to G:\My Drive\Git\class_10623\hw0\handout\wandb\run-20250126_194208-allzpf61\logs\debug-internal.log
2025-01-26 19:42:08,471 INFO    MainThread:37356 [wandb_init.py:init():743] calling init triggers
2025-01-26 19:42:08,471 INFO    MainThread:37356 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {}
2025-01-26 19:42:08,471 INFO    MainThread:37356 [wandb_init.py:init():776] starting backend
2025-01-26 19:42:08,634 WARNING MainThread:37356 [wandb_init.py:init():1448] interrupted
Traceback (most recent call last):
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    service = self._wl.ensure_service()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\wandb_setup.py", line 280, in ensure_service
    self._connection = service_connection.connect_to_service(self._settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\lib\service_connection.py", line 40, in connect_to_service
    return _start_and_connect_service(settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\lib\service_connection.py", line 75, in _start_and_connect_service
    proc.start()
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\service\service.py", line 232, in start
    self._launch_server()
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\service\service.py", line 224, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "C:\Users\82102\anaconda3\envs\class_10623\Lib\site-packages\wandb\sdk\service\service.py", line 105, in _wait_for_ports
    time.sleep(0.2)
KeyboardInterrupt
